- pkg/apis/helm.cattle.io/v1/doc.go
- pkg/apis/helm.cattle.io/v1/types.go
- pkg/helm/controller.go
- pkg/helm/controller_test.go
https://github.com/rancher/klipper-helm/pull/3
> changes for helm v3

- pkg/helm/controller.go
Updating klipper to use the new binaries of helm for v2 and v3
> klipper image update

- pkg/apis/helm.cattle.io/v1/types.go
- pkg/helm/controller.go
- pkg/helm/controller_test.go
https://github.com/rancher/rke2/issues/34
> Add chartcontent spec

- pkg/helm/controller.go
Solution based on th suggestion by @cjellick 
Fixes: https://github.com/rancher/k3s/issues/1807
> add toleration for uninitialized

- pkg/helm/controller.go
> Update klipper-helm version

- pkg/helm/controller.go
- scripts/e2e
- test/suite/helm_test.go
Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>
https://github.com/rancher/rke2/issues/481
depends on https://github.com/rancher/klipper-helm/pull/20
> Pass bootstrap env variable to bootstrap enabled jobs

- .drone.yml
- README.md
- manifests/deploy-cluster-scoped.yaml
- manifests/deploy-namespaced.yaml
- scripts/package
- test/framework/controller.go
image: revert to rancher/helm-controller
Part of rancher/k3s#2189
> image: revert to rancher/helm-controller

- pkg/helm/controller.go
Signed-off-by: Jacob Blain Christen <jacob@rancher.com>
> bump klipper-helm image

- pkg/helm/controller.go
Relate to https://github.com/rancher/rke2/issues/487.
> Fix CriticalAddonsOnly node-taint caused job pend

- pkg/helm/controller.go
Related to k3s-io/k3s#2777 and k3s-io/klipper-helm#24
> Update klipper-helm image to v0.4.2 for stable charts repo URL change

- pkg/helm/controller.go
Related to k3s-io/k3s#2777 and k3s-io/klipper-helm#25
> Update klipper-helm image to v0.4.3 for helm_v2 stable charts repo URL change

- pkg/helm/controller.go
For https://github.com/rancher/rke2/issues/705
> Upgrade klipper-helm image to newest build

- pkg/helm/controller.go
For rancher/rke2#948
~Will need to bump the job image before merging, after k3s-io/klipper-helm#26 is merged and tagged~
> Escape commas in helm set flags

- pkg/helm/controller.go
- pkg/helm/controller_test.go
We were misusing the IntOrStr type and just blindly assuming that
anything with an empty StrVal was an integer, when there is a specific
Type field to tell us if it is an integer or not. We were also less
flexible than Helm when handling booleans, and didn't handle null
properly either.
This should address rancher/rke2#1015
> Fix helm arg processing of empty strings

- pkg/helm/controller.go
https://github.com/rancher/rke2/issues/1061
> Add node role tolerations to bootstrap charts

- pkg/apis/helm.cattle.io/v1/types.go
- pkg/apis/helm.cattle.io/v1/zz_generated_deepcopy.go
- pkg/helm/controller.go
Waiting on merge and tag of https://github.com/k3s-io/klipper-helm/pull/27
For #91
> Add timeout and bump job image

- pkg/helm/controller.go
~Waiting on merge and tag of k3s-io/klipper-helm#28~
> Bump job image to include helm-set-status plugin

- pkg/helm/controller.go
> Bump job image to v0.6.2-build20210803

- pkg/helm/controller.go
> [release-0.10] Bump job image to v0.6.2-build20210803

- pkg/helm/controller.go
Fixes regression caused by 
* k3s-io/klipper-helm#29
> Bump job image for CA cert fix 

- pkg/helm/controller.go
Fixes regression caused by 
* k3s-io/klipper-helm#29
> [release-0.10] Bump job image for CA cert fix

- pkg/helm/controller.go
Bump klipper-helm image for k3s-io/k3s#3843
Waiting on merge and tag of 
* https://github.com/k3s-io/klipper-helm/pull/32
> Bump klipper-helm image for k3s-io/k3s#3843

- pkg/helm/controller.go
Bump klipper-helm image for k3s-io/k3s#3843
Waiting on merge and tag of
* https://github.com/k3s-io/klipper-helm/pull/32
> [release-0.10] Bump klipper-helm image for k3s-io/k3s#3843

- pkg/helm/controller.go
> Add linux nodeSelector to all Helm jobs

- pkg/helm/controller.go
> [release-0.10] Add linux nodeSelector to all Helm jobs

- pkg/helm/controller.go
Waiting for merge and tag of https://github.com/k3s-io/klipper-helm/pull/33
> Bump klipper-helm image version

- pkg/helm/controller.go
Waiting for merge and tag of https://github.com/k3s-io/klipper-helm/pull/33
> [release-0.10] Bump klipper-helm image version

- pkg/helm/controller.go
Related to
* https://github.com/k3s-io/k3s/issues/3994
> Ensure that job pods are deleted immediately when replacing jobs

- pkg/helm/controller.go
* https://github.com/rancher/rke2/issues/2085
Waiting on merge/tag of 
* https://github.com/k3s-io/klipper-helm/pull/39
> bump klipper-helm image tag

- pkg/helm/controller.go
* https://github.com/rancher/rke2/issues/2085
Waiting on merge/tag of 
* https://github.com/k3s-io/klipper-helm/pull/39
> [release-0.10] bump klipper-helm image tag

- scripts/e2e
- test/suite/helm_test.go
Convert e2e tests over to K3s
* #104
> Convert e2e tests over to K3s

- pkg/helm/controller.go
* Pull in https://github.com/k3s-io/klipper-helm/pull/46
> Bump klipper-helm version to fix issue in repoCA support

- pkg/helm/controller.go
- test/suite/helm_test.go
Fixes https://github.com/k3s-io/helm-controller/issues/91#issuecomment-1216428893
> Fix timeout support

- pkg/controllers/chart/chart.go
> Bump klipper-helm image to v0.7.4-build20221121

- .github/dependabot.yml
- .golangci.json
- Dockerfile.dapper
This contributes to https://github.com/k3s-io/k3s/issues/7040.
> Adding dependabot to keep dockerfiles up to date

- pkg/controllers/chart/chart.go
- https://github.com/k3s-io/helm-controller/issues/181
- https://github.com/k3s-io/k3s/issues/7184
> Update klipper-helm to version v0.7.7-build20230403

- pkg/controllers/chart/chart.go
- pkg/controllers/chart/chart_test.go
Fix apply controller thrashing secret data on controller startup
Under certain conditions, the HelmChart controller was observed to quickly apply a change to both the ValuesSecret and the `helmcharts.helm.cattle.io/configHash` on the Job resource.
Watching the secret from another client shows no apparent changes, but for some reason the calculated hash was changing. This in turn kicks off a round of two quick delete and recreates of the Job - one very short-lived with a new hash, and another with the original hash from the previous run of the controller.
There is some weirdness around how Secrets get serialized. Specifically, the stringData field:
https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/
> `stringData (map[string]string)`
> `stringData` …
> Fix apply controller thrashing secret data on controller startup

- pkg/controllers/chart/chart.go
* https://github.com/k3s-io/k3s/issues/9549
> Bump default job image to v0.8.3-build20240228

- pkg/controllers/chart/chart.go
- scripts/e2e
- test/framework/framework.go
- test/suite/helm_test.go
Long, long overdue.
Ref: https://helm.sh/blog/helm-v2-deprecation-timeline/
> Remove helm v2 support

- pkg/apis/helm.cattle.io/v1/types.go
- pkg/controllers/chart/chart.go
For:
* https://github.com/k3s-io/helm-controller/issues/248
* https://github.com/k3s-io/helm-controller/issues/247
Waiting on merge/tag of:
> Add support for skip-verify/plain-http

- pkg/apis/helm.cattle.io/v1/types.go
- pkg/controllers/chart/chart.go
Backport: 
* https://github.com/k3s-io/helm-controller/pull/249
> [release-v0.15] Add support for skip-verify/plain-http

- .drone.yml
https://github.com/k3s-io/helm-controller/pull/263 forgot to change the new Dockerfile location (moved from standalone Dockerfile to target in multistage build).
CI failure example: https://drone-publish.k3s.io/k3s-io/helm-controller/132/2/4
> Fix Docker Publish step
